// Code generated by ifacemaker; DO NOT EDIT.

package otel

import (
	"context"

	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
)

// ExternalConnector defines how to establish a connection between a Crossplane managed resource and its corresponding external system.
type ExternalConnector interface {
	Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error)
}
