// Code generated by ifacemaker; DO NOT EDIT.

package otel

import (
	"context"

	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
)

// ExternalClient defines the interface for interacting with external resources.
type ExternalClient interface {
	Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error)
	Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error)
	Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error)
	Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error)
	Disconnect(ctx context.Context) error
}
