// Code generated by gowrap. DO NOT EDIT.
// template: opentelemetry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package otel

import (
	"context"
	"path"
	"reflect"

	"github.com/angelokurtis/go-otel/span"
	"go.opentelemetry.io/otel/attribute"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	semconv "go.opentelemetry.io/otel/semconv/v1.30.0"
)

// InstrumentedReconciler implements Reconciler interface instrumented with open telemetry spans
type InstrumentedReconciler struct {
	Reconciler
}

// NewInstrumentedReconciler returns InstrumentedReconciler
func NewInstrumentedReconciler(base Reconciler) InstrumentedReconciler {
	return InstrumentedReconciler{
		Reconciler: base,
	}
}

// Reconcile implements Reconciler
func (_d InstrumentedReconciler) Reconcile(ctx context.Context, req reconcile.Request) (result reconcile.Result, err error) {
	t := reflect.TypeOf(_d.Reconciler)
	var pkgPath, pkgName, typeName string
	if t != nil {
		if t.Kind() == reflect.Ptr {
			t = t.Elem() // Dereference pointer to get underlying type
		}
		pkgPath = t.PkgPath()
		pkgName = path.Base(pkgPath)
		typeName = t.Name()
	}
	methodName := "Reconcile"
	spanName := pkgName + "." + typeName + "." + methodName
	ctx, end := span.StartWithName(ctx, spanName)
	defer func() {
		_ = span.Error(ctx, err)
		end()
	}()

	span.Attributes(ctx,
		semconv.CodeNamespace(pkgPath),
		semconv.CodeFunctionName(methodName),
		attribute.Key("code.type").String(typeName),
	)
	return _d.Reconciler.Reconcile(ctx, req)
}
