// Code generated by ifacemaker; DO NOT EDIT.

package otel

import (
	"context"

	"github.com/upbound/provider-opentofu/internal/opentofu"
	. "github.com/upbound/provider-opentofu/internal/opentofu"
)

// OpenTofuClient defines the interface for interacting with an OpenTofu backend.
type OpenTofuClient interface {
	Init(ctx context.Context, o ...InitOption) error
	Validate(ctx context.Context) error
	Workspace(ctx context.Context, name string) error
	DeleteCurrentWorkspace(ctx context.Context) error
	GenerateChecksum(ctx context.Context) (string, error)
	Outputs(ctx context.Context) ([]opentofu.Output, error)
	Resources(ctx context.Context) ([]string, error)
	Diff(ctx context.Context, o ...Option) (bool, error)
	Apply(ctx context.Context, o ...Option) error
	Destroy(ctx context.Context, o ...Option) error
}
