// Code generated by ifacemaker; DO NOT EDIT.

package otel

import (
	"context"

	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// Reconciler defines an interface for Kubernetes controllers that reconcile resources.
type Reconciler interface {
	Reconcile(ctx context.Context, req reconcile.Request) (result reconcile.Result, err error)
}
